#!/usr/bin/env python3
"""
Generate func_table_gen.cpp from the declarations in recomp/ppu_recomp.h.

Stopgap for the current lift: the function table emitted inside ppu_recomp.c
is `static` (file-local), so the dispatcher can't link against it. This tool
rebuilds the same addr->func mapping from the header's declarations, which
all have external linkage. Once a relift with the fixed lifter lands (table
emitted non-static + declared in the header), this generator and its output
can be dropped in favor of `function_table` directly.

Usage:  py -3 gen_func_table.py [path/to/ppu_recomp.h] [out.cpp]
"""

import re
import sys
import os

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    header = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "recomp", "ppu_recomp.h")
    out    = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "func_table_gen.cpp")

    pat = re.compile(r"^void (func_([0-9A-Fa-f]{8}))\(ppu_context\* ctx\);")
    entries = {}
    with open(header, "r", encoding="utf-8") as f:
        for line in f:
            m = pat.match(line)
            if m:
                entries[int(m.group(2), 16)] = m.group(1)

    if not entries:
        sys.exit("no func_XXXXXXXX declarations found in " + header)

    lines = []
    lines.append("/* Auto-generated by gen_func_table.py from ppu_recomp.h -- do not edit. */")
    lines.append('#include "ppu_recomp.h"')
    lines.append("")
    lines.append('#include "yakuza_runner.h"')
    lines.append("")
    lines.append("const yz_func_entry g_yz_func_table[] = {")
    for addr in sorted(entries):
        lines.append(f"    {{ 0x{addr:08X}u, {entries[addr]} }},")
    lines.append("};")
    lines.append(f"const unsigned g_yz_func_count = {len(entries)}u;")
    lines.append("")

    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: {len(entries)} entries (sorted by address)")

if __name__ == "__main__":
    main()
