#!/usr/bin/env python3
"""
Generate func_table_gen.cpp from the declarations in the lifted headers.

Stopgap for the current lift: the function table emitted inside ppu_recomp.c
is `static` (file-local), so the dispatcher can't link against it. This tool
rebuilds the same addr->func mapping from the headers' declarations, which
all have external linkage. Once a relift with the fixed lifter lands (table
emitted non-static + declared in the header), this generator and its output
can be dropped in favor of `function_table` directly.

Multiple headers are merged into one table (the game lift + LLE-lifted
firmware PRX modules such as libsre). Only the first header is #included in
the output (the generated headers each redefine ppu_context and cannot
coexist in one TU); functions declared only in later headers get their own
extern "C" declarations emitted directly.

Usage:  py -3 gen_func_table.py [header ...] [-o out.cpp]
        (defaults: ../recomp/ppu_recomp.h ../recomp_prx/libsre_recomp.h)
"""

import re
import sys
import os

def parse_decls(path):
    pat = re.compile(r"^void (func_([0-9A-Fa-f]{8}))\(ppu_context\* ctx\);", re.M)
    with open(path, "r", encoding="utf-8") as f:
        return {int(m.group(2), 16): m.group(1) for m in pat.finditer(f.read())}

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    args = sys.argv[1:]
    out = os.path.join(here, "func_table_gen.cpp")
    if "-o" in args:
        i = args.index("-o")
        out = args[i + 1]
        del args[i:i + 2]
    headers = args or [
        os.path.join(here, "..", "recomp", "ppu_recomp.h"),
        os.path.join(here, "..", "recomp_prx", "libsre_recomp.h"),
    ]
    headers = [h for h in headers if os.path.exists(h)] or sys.exit("no headers found")

    primary = parse_decls(headers[0])
    if not primary:
        sys.exit("no func_XXXXXXXX declarations found in " + headers[0])
    entries = dict(primary)
    extra = {}  # declared only in secondary headers -> need explicit decls
    for h in headers[1:]:
        for addr, name in parse_decls(h).items():
            if addr not in entries:
                entries[addr] = name
                extra[addr] = name

    lines = []
    lines.append("/* Auto-generated by gen_func_table.py from "
                 + ", ".join(os.path.basename(h) for h in headers)
                 + " -- do not edit. */")
    lines.append('#include "ppu_recomp.h"')
    lines.append("")
    lines.append('#include "yakuza_runner.h"')
    lines.append("")
    if extra:
        lines.append("/* Declared in secondary lifted headers (not includable "
                     "alongside ppu_recomp.h). C++ linkage, same as the "
                     "headers' own declarations. */")
        for addr in sorted(extra):
            lines.append(f"void {extra[addr]}(ppu_context* ctx);")
        lines.append("")
    lines.append("const yz_func_entry g_yz_func_table[] = {")
    for addr in sorted(entries):
        lines.append(f"    {{ 0x{addr:08X}u, {entries[addr]} }},")
    lines.append("};")
    lines.append(f"const unsigned g_yz_func_count = {len(entries)}u;")
    lines.append("")

    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: {len(entries)} entries "
          f"({len(primary)} primary + {len(extra)} secondary), sorted by address")

if __name__ == "__main__":
    main()
