/*
 * Yakuza: Dead Souls -- recomp runner, shared declarations.
 *
 * Translation-unit layout (deliberate):
 *   - main.cpp / dispatch.cpp / func_table_gen.cpp include the GENERATED
 *     ppu_recomp.h (its ppu_context layout is what ppu_recomp.obj was
 *     compiled against).
 *   - shims.cpp includes the RUNTIME headers instead (runtime ppu_context).
 *     The two struct layouts agree for gpr/fpr/vr/cr/lr/ctr (offsets 0..1047),
 *     which is all the lv2 syscall handlers touch in practice; the tail
 *     fields diverge (see STATUS.md "context layout" note).
 * This header therefore only forward-declares ppu_context.
 */
#pragma once

#include <stdint.h>
#include <stddef.h>

struct ppu_context;
typedef struct ppu_context ppu_context;

typedef void (*yz_ppu_fn)(ppu_context*);

/* Live guest context for the current host thread (defined in main.cpp). Set at
 * each guest-thread entry / callback so the crash handler can walk the guest
 * PPC64 back-chain. */
extern thread_local ppu_context* g_yz_cur_ctx;

/* Generated by gen_func_table.py -- sorted by addr, no sentinel. */
struct yz_func_entry {
    uint32_t addr;
    yz_ppu_fn fn;
};
extern const yz_func_entry g_yz_func_table[];
extern const unsigned      g_yz_func_count;

/* dispatch.cpp */
extern "C" yz_ppu_fn yz_lookup_func(uint32_t guest_addr);   /* NULL if unknown */
extern "C" void      yz_drain_trampolines(ppu_context* ctx);
/* Call a guest function through an OPD descriptor (sets r2, drains). */
extern "C" void      yz_call_guest_opd(uint32_t opd_addr, ppu_context* ctx);

/* shims.cpp */
extern "C" void yz_init_syscalls(void);

/* threads.cpp -- PPU thread runtime */
extern "C" void     yz_threads_init(uint32_t main_stack_base,
                                    uint32_t main_stack_size);
extern "C" uint32_t yz_thread_current_id(void);
extern "C" int64_t  yz_sc_thread_yield(ppu_context* ctx);
extern "C" int64_t  yz_sc_thread_join(ppu_context* ctx);
extern "C" int64_t  yz_sc_thread_set_priority(ppu_context* ctx);
extern "C" int64_t  yz_sc_thread_get_priority(ppu_context* ctx);
extern "C" int64_t  yz_sc_thread_get_stack_information(ppu_context* ctx);

/* import_bridges_gen.cpp (generated by gen_imports.py) -----------------------
 * Each imported firmware function gets a synthetic OPD in guest scratch
 * memory whose code address is a fake key that routes ps3_indirect_call to
 * a host bridge. The fake range is never dereferenced as memory. */
#define YZ_IMPORT_OPD_BASE  0x0FF00000u
#define YZ_IMPORT_FAKE_BASE 0xFE000000u
extern "C" void  yz_install_imports(void);
extern yz_ppu_fn g_yz_import_bridges[];
extern const unsigned g_yz_import_count;
extern const char* const g_yz_import_names[];
extern const unsigned g_yz_lle_import_first;

/* LLE firmware modules ---------------------------------------------------------
 * Sony's libsre (cellSpurs/cellSync/cellDaisy/cellSheap/cellOvis), decrypted
 * from firmware and relocated to a fixed guest base by tools/lift_prx.py,
 * then lifted alongside the game (recomp_prx/). The flat image includes the
 * zero-filled bss tail; the game's SPURS-family imports bind to its export
 * OPDs and its own 32 import slots are patched by yz_install_imports(). */
#define YZ_LIBSRE_BASE 0x02000000u

/* gcm guest-side structures (import_overrides.cpp) ----------------------------
 * _cellGcmInitBody builds these in runner scratch. The game's SDK-inline gcm
 * code walks CellGcmContextData in guest memory itself (EBOOT layout, verified
 * from func_00EBC0C8/EBC128: begin@+0, end@+4, current@+8, callback@+0xC; the
 * callback field holds an OPD whose code word the game mtctr/bctrl's). */
#define YZ_GCM_CTX_ADDR     0x0FF80000u  /* CellGcmContextData (16 B) */
#define YZ_GCM_CB_OPD_ADDR  0x0FF80020u  /* synthetic OPD for the fifo callback */
#define YZ_GCM_CTRL_ADDR    0x0FF80040u  /* CellGcmControl put/get/ref */
#define YZ_GCM_LABELS_ADDR  0x0FF81000u  /* RSX label area, 256 x 16 B */
#define YZ_GCM_CB_FAKE_KEY  0xFE100000u  /* routed by import_bridge_for() */
#define YZ_GCM_LOCAL_BASE   0xC0000000u  /* RSX local memory (matches libs) */
#define YZ_GCM_LOCAL_SIZE   0x0F900000u  /* 249 MB, real-hardware value */
extern "C" void yz_gcm_fifo_callback(ppu_context* ctx);
