/*
 * Yakuza: Dead Souls -- recomp runner, shared declarations.
 *
 * Translation-unit layout (deliberate):
 *   - main.cpp / dispatch.cpp / func_table_gen.cpp include the GENERATED
 *     ppu_recomp.h (its ppu_context layout is what ppu_recomp.obj was
 *     compiled against).
 *   - shims.cpp includes the RUNTIME headers instead (runtime ppu_context).
 *     The two struct layouts agree for gpr/fpr/vr/cr/lr/ctr (offsets 0..1047),
 *     which is all the lv2 syscall handlers touch in practice; the tail
 *     fields diverge (see STATUS.md "context layout" note).
 * This header therefore only forward-declares ppu_context.
 */
#pragma once

#include <stdint.h>
#include <stddef.h>

struct ppu_context;
typedef struct ppu_context ppu_context;

typedef void (*yz_ppu_fn)(ppu_context*);

/* Generated by gen_func_table.py -- sorted by addr, no sentinel. */
struct yz_func_entry {
    uint32_t addr;
    yz_ppu_fn fn;
};
extern const yz_func_entry g_yz_func_table[];
extern const unsigned      g_yz_func_count;

/* dispatch.cpp */
extern "C" yz_ppu_fn yz_lookup_func(uint32_t guest_addr);   /* NULL if unknown */
extern "C" void      yz_drain_trampolines(ppu_context* ctx);
/* Call a guest function through an OPD descriptor (sets r2, drains). */
extern "C" void      yz_call_guest_opd(uint32_t opd_addr, ppu_context* ctx);

/* shims.cpp */
extern "C" void yz_init_syscalls(void);

/* import_bridges_gen.cpp (generated by gen_imports.py) -----------------------
 * Each imported firmware function gets a synthetic OPD in guest scratch
 * memory whose code address is a fake key that routes ps3_indirect_call to
 * a host bridge. The fake range is never dereferenced as memory. */
#define YZ_IMPORT_OPD_BASE  0x0FF00000u
#define YZ_IMPORT_FAKE_BASE 0xFE000000u
extern "C" void  yz_install_imports(void);
extern yz_ppu_fn g_yz_import_bridges[];
extern const unsigned g_yz_import_count;
