#!/usr/bin/env python3
"""Batch SPU image lift + generated registration table.

Lifts every EBOOT SPU image in scratch/spu_imgs/ that is not yet lifted, and
generates recomp_prx/spu_image_table.h -- a single table {elf EA, image id,
entry, name, BSS spans, register fn} consumed by the runtime (spu_channels.c
elf->image mapping + fresh-start BSS zero-fill) and main.cpp (registration).
Replaces the per-image hand-derivation (entry/BSS/wiring) that made each new
image an hour of work: parameters come straight from the ELF headers (the
formula reproduces the three hand-derived images byte-exactly, 2026-07-02).

Image-id assignment is PINNED for the three pre-existing images (their ids are
baked into probe/flag semantics): gs_task=0, cri_audio=3, wkl4=4. Firmware
images (kernel=0-wildcard, service=1, policy=2) are NOT in this table. New
EBOOT images get ids from 5 upward in filename order.

Usage:
    py -3 tools\\gen_spu_images.py            # lift missing + regenerate table
    py -3 tools\\gen_spu_images.py --force    # relift everything
"""

import argparse
import glob
import os
import struct
import subprocess
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
IMG_DIR = os.path.join(ROOT, "scratch", "spu_imgs")
OUT_DIR = os.path.join(ROOT, "recomp_prx")

# The three images lifted before this generator existed keep their module
# names, register functions, and image ids (probe semantics depend on them).
PINNED = {
    0x0127A580: dict(image_id=0, name="gs_task",   src="gs_task.c",
                     prefix="spu_func_", register="spu_recomp_register_gstask",
                     lift=False),   # pre-existing lift; never relifted here
    0x012B4980: dict(image_id=3, name="cri_audio", src="cri_audio.c",
                     prefix="cri_audio_", register="cri_audio_register_functions",
                     lift=False),
    0x01284200: dict(image_id=4, name="wkl4",      src="wkl4_task.c",
                     prefix="wkl4_", register="wkl4_register_functions",
                     lift=False),
}
NEXT_ID = 5


def parse_elf(path):
    d = open(path, "rb").read()
    entry = struct.unpack_from(">I", d, 24)[0]
    phoff = struct.unpack_from(">I", d, 28)[0]
    phnum = struct.unpack_from(">H", d, 44)[0]
    bss = []
    for i in range(phnum):
        t, off, va, pa, fsz, msz, fl, al = struct.unpack_from(">8I", d, phoff + i * 32)
        if t == 1 and msz > fsz:
            bss.append((va + fsz, msz - fsz))
    return entry, bss


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="relift even if the .c exists")
    args = ap.parse_args()

    images = []
    next_id = NEXT_ID
    for path in sorted(glob.glob(os.path.join(IMG_DIR, "spu_*_at_*.elf"))):
        base = os.path.basename(path)
        file_ea = int(base.split("_at_")[1].split(".")[0], 16)
        elf_ea = file_ea + 0x10000            # EBOOT load bias (verified x3)
        entry, bss = parse_elf(path)
        if elf_ea in PINNED:
            info = dict(PINNED[elf_ea])
        else:
            n = base.split("_")[1]            # '0006'
            info = dict(image_id=next_id, name=f"spuimg{int(n)}",
                        src=f"spuimg_{int(n):02d}.c",
                        prefix=f"spuimg{int(n)}_",
                        register=f"spuimg{int(n)}_register_functions",
                        lift=True)
            next_id += 1
        info.update(elf_ea=elf_ea, entry=entry, bss=bss, path=path)
        images.append(info)

    # ---- lift the ones this generator owns --------------------------------
    for im in images:
        if not im["lift"]:
            continue
        src = os.path.join(OUT_DIR, im["src"])
        if os.path.exists(src) and not args.force:
            continue
        hdr = im["src"].replace(".c", ".h")
        cmd = [sys.executable, os.path.join(TOOLS, "spu_lifter.py"),
               "--auto-functions", im["path"], "--seed-all",
               "--func-prefix", im["prefix"],
               "--register-name", im["register"],
               "--output", OUT_DIR, "--source-name", im["src"],
               "--header-name", hdr]
        print(f"[lift] {im['name']} (elf 0x{im['elf_ea']:08X}, entry 0x{im['entry']:X})")
        r = subprocess.run(cmd, capture_output=True, text=True)
        tail = (r.stdout or "").strip().splitlines()
        print("   " + (tail[-1] if tail else "(no output)"))
        if r.returncode != 0:
            print(f"   LIFT FAILED for {im['name']}: {(r.stderr or '')[-300:]}")
            im["failed"] = True

    ok = [im for im in images if not im.get("failed")]

    # ---- the table header --------------------------------------------------
    h = os.path.join(OUT_DIR, "spu_image_table.h")
    L = ["/* Auto-generated by tools/gen_spu_images.py -- do not edit by hand. */",
         "#pragma once", "#include <stdint.h>", "#include <string.h>", "",
         "#ifdef __cplusplus", 'extern "C" {', "#endif", "",
         "typedef struct spu_image_desc {",
         "    uint32_t elf_ea;     /* EBOOT EA the taskInfo elf field carries */",
         "    int      image_id;   /* runtime dispatch image id */",
         "    uint32_t entry;      /* ELF e_entry (fresh-start pc) */",
         "    const char* name;",
         "    uint32_t bss_va[4];  /* [filesz,memsz) spans, ELF contract zero-fill */",
         "    uint32_t bss_len[4];",
         "    int      bss_n;",
         "} spu_image_desc;", "",
         f"#define SPU_IMAGE_COUNT {len(ok)}",
         "static const spu_image_desc g_spu_images[SPU_IMAGE_COUNT] = {"]
    for im in ok:
        vas = [f"0x{a:X}u" for a, _ in im["bss"]] + ["0"] * (4 - len(im["bss"]))
        ls = [f"0x{l:X}u" for _, l in im["bss"]] + ["0"] * (4 - len(im["bss"]))
        L.append(f'    {{ 0x{im["elf_ea"]:08X}u, {im["image_id"]}, 0x{im["entry"]:X}u, '
                 f'"{im["name"]}", {{{", ".join(vas)}}}, {{{", ".join(ls)}}}, {len(im["bss"])} }},')
    L += ["};", "",
          "/* elf EA -> table entry (NULL if unknown). */",
          "static inline const spu_image_desc* spu_image_for_elf(uint32_t elf_ea) {",
          "    for (int i = 0; i < SPU_IMAGE_COUNT; i++)",
          "        if (g_spu_images[i].elf_ea == elf_ea) return &g_spu_images[i];",
          "    return (const spu_image_desc*)0;",
          "}",
          "static inline const spu_image_desc* spu_image_for_id(int image_id) {",
          "    for (int i = 0; i < SPU_IMAGE_COUNT; i++)",
          "        if (g_spu_images[i].image_id == image_id) return &g_spu_images[i];",
          "    return (const spu_image_desc*)0;",
          "}",
          "/* ELF-contract fresh-start zero-fill of the image's BSS spans in an LS. */",
          "static inline void spu_image_zero_bss(uint8_t* ls, const spu_image_desc* d) {",
          "    for (int i = 0; i < d->bss_n; i++)",
          "        memset(ls + d->bss_va[i], 0, d->bss_len[i]);",
          "}", ""]
    # registration of the generator-owned images (pinned ones stay explicit in main.cpp)
    L.append("/* Register the generator-owned images (called from main.cpp after the")
    L.append(" * explicit kernel/service/policy/cri_audio registrations). */")
    for im in ok:
        if im["lift"]:
            L.append(f"void {im['register']}(void);")
    L.append("void spu_begin_image(int image_id);")
    L.append("static inline void spu_images_register_extra(void) {")
    for im in ok:
        if im["lift"]:
            L.append(f"    spu_begin_image({im['image_id']}); {im['register']}();")
    L += ["}", "", "#ifdef __cplusplus", "}", "#endif", ""]
    with open(h, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {h}: {len(ok)} images "
          f"({sum(1 for im in ok if im['lift'])} generator-owned)")


if __name__ == "__main__":
    main()
