#!/usr/bin/env python3
"""Generate the SPU interpreter's decoder (runtime/spu/spu_interp_gen.h) by
PROBING tools/spu_disasm.py — the already-debugged decode tables + priority
order stay the single source of truth (2026-07-01 reassessment, item 3a).

Every SPU instruction format is distinguishable by the top 11 bits, so the
whole opcode space is one 2048-entry table: op11 -> (operation, format).
We probe the real disassembler at each op11 (insn = op11 << 21) so the C
table inherits the Python decoder's exact priority order (RRR before RI18
before RI16 before channel before RI10 before RI8 before RR/RI7) — the
class of decode-order bug that has burned this project cannot re-diverge.

Usage:  py -3 tools/gen_spu_interp.py   (writes runtime/spu/spu_interp_gen.h)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import spu_disasm as D

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "runtime", "spu", "spu_interp_gen.h")

# format tags (field layout the C side extracts for each)
FMT_RR, FMT_RRR, FMT_RI7, FMT_RI8, FMT_RI10, FMT_RI16, FMT_RI18, FMT_CH = range(8)
FMT_NAMES = ["SPU_FMT_RR", "SPU_FMT_RRR", "SPU_FMT_RI7", "SPU_FMT_RI8",
             "SPU_FMT_RI10", "SPU_FMT_RI16", "SPU_FMT_RI18", "SPU_FMT_CH"]

# stable ISA fact: the RI7 mnemonics (local table inside spu_disasm.decode)
RI7_MNEMONICS = {
    "roti", "rotmi", "rotmai", "shli", "rothi", "rothmi", "rotmahi", "shlhi",
    "cbd", "chd", "cwd", "cdd",
    "rotqbii", "rotqmbii", "shlqbii", "rotqbyi", "rotqmbyi", "shlqbyi",
}
RI8_MNEMONICS = {"cflts", "cfltu", "csflt", "cuflt"}
CH_MNEMONICS = {"rdch", "wrch", "rchcnt"}


def classify(mne):
    if mne in D.RRR_TABLE.values():
        return FMT_RRR
    if mne in D.RI18_TABLE.values():
        return FMT_RI18
    if mne in D.RI16_TABLE.values():
        return FMT_RI16
    if mne in CH_MNEMONICS:
        return FMT_CH
    if mne in D.RI10_TABLE.values():
        return FMT_RI10
    if mne in RI8_MNEMONICS:
        return FMT_RI8
    if mne in RI7_MNEMONICS:
        return FMT_RI7
    return FMT_RR


def main():
    ops = {}          # mnemonic -> enum index (0 = unknown)
    table = []        # 2048 x (opname, fmt)
    for op11 in range(2048):
        insn = op11 << 21
        r = D.spu_decode(insn, 0)
        mne = getattr(r, "mnemonic", None)
        if not mne or mne.startswith(".") or mne == "unknown":
            table.append((None, FMT_RR))
            continue
        ops.setdefault(mne, len(ops) + 1)
        table.append((mne, classify(mne)))

    names = sorted(ops, key=ops.get)
    with open(OUT, "w", newline="\n") as f:
        w = f.write
        w("/* GENERATED by tools/gen_spu_interp.py -- DO NOT hand-edit.\n"
          " * Decoder facts probed from tools/spu_disasm.py (single source of\n"
          " * truth for SPU decode; regenerate after any disasm table change).\n"
          " * %d operations, full op11 space mapped. */\n" % len(names))
        w("#ifndef SPU_INTERP_GEN_H\n#define SPU_INTERP_GEN_H\n\n#include <stdint.h>\n\n")
        w("enum spu_fmt { SPU_FMT_RR, SPU_FMT_RRR, SPU_FMT_RI7, SPU_FMT_RI8,\n"
          "               SPU_FMT_RI10, SPU_FMT_RI16, SPU_FMT_RI18, SPU_FMT_CH };\n\n")
        w("enum spu_iop {\n    SPU_IOP_UNKNOWN = 0,\n")
        for i, n in enumerate(names):
            w("    SPU_IOP_%s = %d,\n" % (n.upper(), i + 1))
        w("    SPU_IOP__COUNT\n};\n\n")
        w("static const char* const spu_iop_name[SPU_IOP__COUNT] = {\n    \"unknown\",\n")
        for n in names:
            w("    \"%s\",\n" % n)
        w("};\n\n")
        w("/* op11 (insn >> 21) -> { operation, format } */\n")
        w("typedef struct { uint16_t op; uint8_t fmt; } spu_op11_ent;\n")
        w("static const spu_op11_ent spu_op11_map[2048] = {\n")
        for i in range(0, 2048, 4):
            row = []
            for j in range(4):
                mne, fmt = table[i + j]
                op = ("SPU_IOP_" + mne.upper()) if mne else "SPU_IOP_UNKNOWN"
                row.append("{%s,%s}" % (op, FMT_NAMES[fmt]))
            w("    %s,\n" % ", ".join(row))
        w("};\n\n")
        w("""/* Decoded instruction: every field extracted; semantics pick what they use. */
typedef struct {
    uint16_t op;     /* enum spu_iop */
    uint8_t  fmt;    /* enum spu_fmt */
    uint8_t  rt, ra, rb, rc;   /* rc = RRR dest (bits 21-27); rt = bits 0-6 */
    uint8_t  ch;     /* channel field (bits 7-11) for FMT_CH */
    int32_t  i7;     /* sign-extended 7-bit imm (bits 14-20) */
    uint32_t i8;     /* 8-bit imm (bits 14-21), RI8 scale */
    int32_t  i10;    /* sign-extended 10-bit imm (bits 14-23) */
    int32_t  i16;    /* sign-extended 16-bit imm (bits 7-22) */
    uint32_t i18;    /* 18-bit imm (bits 7-24) */
} spu_insn;

static inline int32_t spu_sext(uint32_t v, int bits)
{
    uint32_t m = 1u << (bits - 1);
    return (int32_t)((v ^ m) - m);
}

static inline void spu_decode(uint32_t insn, spu_insn* d)
{
    const spu_op11_ent e = spu_op11_map[(insn >> 21) & 0x7FF];
    d->op  = e.op;
    d->fmt = e.fmt;
    d->rt  = insn & 0x7F;
    d->ra  = (insn >> 7) & 0x7F;
    d->rb  = (insn >> 14) & 0x7F;
    d->rc  = (insn >> 21) & 0x7F;
    d->ch  = (insn >> 7) & 0x1F;
    d->i7  = spu_sext((insn >> 14) & 0x7F, 7);
    d->i8  = (insn >> 14) & 0xFF;
    d->i10 = spu_sext((insn >> 14) & 0x3FF, 10);
    d->i16 = spu_sext((insn >> 7) & 0xFFFF, 16);
    d->i18 = (insn >> 7) & 0x3FFFF;
}

#endif /* SPU_INTERP_GEN_H */
""")
    print("wrote %s (%d ops)" % (os.path.normpath(OUT), len(names)))


if __name__ == "__main__":
    main()
