#!/usr/bin/env python3
"""
SPU instruction lifter -- translates SPU disassembly into C code for the
ps3recomp static-recompilation runtime.

Mirrors the design of ppu_lifter.py:
  * Each original SPU function is emitted as a C function taking a
    ``spu_context*`` parameter (see runtime/spu/spu_context.h).
  * Instruction semantics live in small ``static inline u128 spu_*`` helper
    functions emitted into the source preamble; the per-instruction
    translator just wires guest registers to those helpers.  This keeps the
    generated function bodies readable and the semantics unit-testable.
  * Control flow uses the same trampoline pattern as the PPU lifter to avoid
    unbounded host-stack growth on backward branches.

SPU register model
------------------
  * 128 registers, each a 128-bit ``u128`` union (lanes: _u32[4], _u16[8],
    _u8[16], _s32[4], _f32[4], ...).
  * Most arithmetic is SIMD across the natural lane width (word = 4x32,
    halfword = 8x16, byte = 16x8).
  * Scalar / addressing instructions use the *preferred slot* = word lane 0
    (``reg._u32[0]``), matching spu_preferred_u32() in spu_context.h.

Scope (Phase 1)
---------------
Implemented faithfully: immediates, integer add/sub (word+half, +imm),
bitwise logic (+imm), compares (eq/gt/lgt for byte/half/word, +imm), select
(selb), byte shuffle (shufb), count-leading-zeros / popcount, the common
shift/rotate-immediate forms, single-precision float add/sub/mul and the
fused multiply forms, quadword load/store (d-form, absolute, indexed),
branches (relative/absolute/conditional/indirect, with link), stop/nop/sync.

Emitted as runtime calls (declared extern, implemented by the runtime):
channel ops (rdch/wrch/rchcnt -> MFC DMA, mailboxes, signals) and indirect
branch dispatch.

Anything not yet handled is emitted as a ``/* TODO spu: ... */`` comment so
the gap is visible in the generated source and counted in the CLI summary.

Usage:
    python spu_lifter.py <input_bin> [--base ADDR] [--output dir]
                         [--functions FILE]
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from spu_disasm import SPUInstruction, disassemble_spu, spu_decode, CHANNEL_NAMES
except ImportError:
    print("Error: spu_disasm.py must be in the same directory.", file=sys.stderr)
    sys.exit(1)

# Channel macro names defined in runtime/spu/spu_context.h. When the
# disassembler hands us one of these, we can emit it verbatim as a macro.
_CHANNEL_MACROS = set(CHANNEL_NAMES.values())

# ---------------------------------------------------------------------------
# C preambles
# ---------------------------------------------------------------------------

HEADER_PREAMBLE = """\
/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "spu_context.h"   /* add runtime/spu to the include path */

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif
"""

# NOTE on endianness: spu_context.h treats word lane 0 as the preferred slot
# and its local-store helpers copy raw bytes (big-endian in the guest image).
# The helpers below operate lane-wise, which is internally consistent as long
# as loads/stores use the same lane convention. A host that is not big-endian
# will need byte-swapping in the LS helpers -- that is a runtime concern, out
# of scope for the lifter.
SOURCE_PREAMBLE = """/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "{header_name}"
#include "spu_helpers.h"
"""

# ---------------------------------------------------------------------------
# Operand helpers
# ---------------------------------------------------------------------------

def _ops(operands: str) -> list[str]:
    return [o.strip() for o in operands.split(",") if o.strip()]


def _reg(token: str) -> str:
    """'$r12' -> '12'."""
    m = re.match(r"\$r(\d+)", token.strip())
    return m.group(1) if m else token.strip()


def _disp_base(token: str):
    """'0x10($r4)' or '-0x10($r4)' -> ('0x10', '4')."""
    m = re.match(r"(-?0x[0-9A-Fa-f]+|-?\d+)\(\$r(\d+)\)", token.strip())
    if m:
        return m.group(1), m.group(2)
    return None, None


def _imm(token: str) -> str:
    token = token.strip()
    if token.startswith("0x") or token.startswith("-0x"):
        return token
    try:
        return str(int(token))
    except ValueError:
        return token


def _chan(token: str) -> str:
    """Channel operand -> a C expression (macro name or numeric id)."""
    token = token.strip()
    if token in _CHANNEL_MACROS:
        return token
    m = re.match(r"ch(\d+)", token)
    if m:
        return m.group(1)
    return token

# ---------------------------------------------------------------------------
# Lifter
# ---------------------------------------------------------------------------

@dataclass
class LiftedFunction:
    name: str = ""
    start_addr: int = 0
    end_addr: int = 0
    body_lines: list[str] = field(default_factory=list)
    calls: list[int] = field(default_factory=list)


# Mnemonics whose last operand is a branch target address (0x...).
_COND_BR = {"brz", "brnz", "brhz", "brhnz"}


# Mnemonics that do NOT write the rt register (so we skip the post-trace).
# Everything else writes rt = ops[0] (= insn.raw & 0x7F).
_NO_RT_WRITE = {
    "stop", "stopd", "lnop", "nop", "sync", "syncc", "dsync",
    "bi", "iret", "biz", "binz", "bihz", "bihnz",
    "br", "bra", "brz", "brnz", "brhz", "brhnz",
    "hbr", "hbra", "hbrr",
    "stqd", "stqa", "stqr", "stqx",
    "wrch",
    "hgt", "hlgt", "heq", "hgti", "hlgti", "heqi",
}

# Call ops that write the LINK register. With --trace they self-emit the link's
# trace_rt BEFORE the nested callee call (so it's logged AT the call PC, like
# RPCS3's BRSL), so the generic post-loop must NOT also trace them -- that would
# log the link AFTER the whole callee ran = a false register divergence.
_LINK_OPS = {"brsl", "brasl", "bisl", "bisled"}


def _bi_target_reg(insn):
    """Return the branch-target register of a bi/biz/binz/... insn, or None."""
    ops = _ops(insn.operands)
    if insn.mnemonic == "bi" and ops:
        return _reg(ops[0])
    if insn.mnemonic in ("biz", "binz", "bihz", "bihnz") and len(ops) >= 2:
        return _reg(ops[1])
    return None


# RRR (4-operand) SPU ops write their destination in bits 21-27; the low 7 bits
# (raw & 0x7F) are the RC *source* for these. Every other format writes bits 0-6.
_RRR_DEST_OPS = {"selb", "shufb", "mpya", "fnms", "fma", "fms"}

def _dest_reg(insn) -> int:
    """The register an instruction writes (rt), accounting for RRR-format ops
    whose destination is bits 21-27 rather than the low 7 bits."""
    if insn.mnemonic in _RRR_DEST_OPS:
        return (insn.raw >> 21) & 0x7F
    return insn.raw & 0x7F


def compute_bi_r0_jumps(insns, logical_bounds) -> set:
    """`bi $r0` (and conditional `biz/binz $r0`) is normally a function RETURN
    (r0 = link register). But Sony's SPU code also uses it as a COMPUTED TAIL
    JUMP after reloading r0 from memory -- e.g. the SPURS taskset launch
    `lqa $r0, savedContextLr(0x2C80) ... bi $r0` jumps to the task entry (0x3050),
    NOT back to the caller. Mistranslating that as `return;` makes the launch
    fall through and the dispatcher loop forever (same bug class as the brsl
    mislifts). Detect it: within each LOGICAL function, a `bi $r0` is a computed
    jump iff the NEAREST preceding write to r0 is an ABSOLUTE load (lqa/lqr).
    A genuine return restores the link via a register/stack load (lqd/lqx) or
    never rewrites r0 -- those stay returns. Returns the set of such bi addrs."""
    jumps = set()
    for (s, e) in logical_bounds:
        fn = sorted((i for i in insns if s <= i.addr < e), key=lambda x: x.addr)
        for idx, insn in enumerate(fn):
            if _bi_target_reg(insn) != "0":
                continue
            # backward scan for the nearest instruction that writes r0
            for j in range(idx - 1, -1, -1):
                w = fn[j]
                if w.mnemonic not in _NO_RT_WRITE and _dest_reg(w) == 0:
                    if w.mnemonic in ("lqa", "lqr"):
                        jumps.add(insn.addr)
                    break  # nearest r0 writer found; classification decided
    return jumps


def form_regions(insns: list[SPUInstruction], region_starts: set, cap: int) -> list[tuple[int, int]]:
    """s41 SPU REGION LIFT (--regions): split the (dense, 4-aligned) image
    instruction stream into regions per the reviewed design -- split at (a)
    known function starts (`region_starts`: REAL subroutine-entry addresses --
    see main()'s construction of this set, which is deliberately narrower than
    find_spu_functions' full --seed-all seed list; design mechanic 1 is
    explicit that plain branch targets are NOT a split, only function starts
    are) and (b) a size cap, cutting wherever the cap is hit. Every cut point
    is safe: lift_region() labels and cases EVERY pc, and a branch/call whose
    target lands in the adjacent region degrades to the existing cross-region
    trampoline/call path rather than an illegal cross-function goto (design
    [REV] 3, review (d)). Returns a sorted list of (start, end) tuples that
    partitions every insn address exactly once.
    """
    addrs = sorted(i.addr for i in insns)
    if not addrs:
        return []
    starts = set(region_starts)
    regions: list[tuple[int, int]] = []
    region_start = addrs[0]
    count = 0
    for idx, a in enumerate(addrs):
        if a != region_start and a in starts:
            regions.append((region_start, a))
            region_start = a
            count = 0
        count += 1
        if count >= cap and idx + 1 < len(addrs):
            nxt = addrs[idx + 1]
            if nxt == a + 4:   # contiguous -- safe to cut cleanly here
                regions.append((region_start, nxt))
                region_start = nxt
                count = 0
    regions.append((region_start, addrs[-1] + 4))
    return regions


class SPULifter:
    def __init__(self, trace: bool = False):
        self.functions: list[LiftedFunction] = []
        self.call_targets: set[int] = set()
        self.branch_targets: set[int] = set()
        self.unsupported: dict[str, int] = {}
        # brsl/brasl whose target could not be resolved and lifted as a no-op
        # (a MISCOMPILE: the call is silently dropped). Warned loudly in the
        # summary — 18 silent no-op calls in job_bin_b were the 2026-07-08
        # round-1 early-exit.
        self.unresolved_calls: list[int] = []
        self.trace = trace
        # s41 SPU REGION LIFT (--regions): count of cross-region call/branch
        # targets that were NOT found in the region owner map and had to fall
        # back to the global spu_indirect_branch dispatch (safe, but should be
        # ~0 for a fully-covered single-image lift like gs_task -- surfaced in
        # the CLI summary so a nonzero count is visible, not silent).
        self.region_fallback_hits = 0
        self.header_name = "spu_recomp.h"   # what emit_source #includes
        self.register_name = "spu_recomp_register"  # global init fn name
        # Per-image C symbol prefix for the emitted functions. Images that load
        # to OVERLAPPING LS addresses (e.g. the SPURS system service and a
        # taskset policy module both at LS 0xA00) would otherwise emit colliding
        # `spu_func_<addr>` symbols and fail to link. Give each its own prefix.
        self.func_prefix = "spu_func_"
        # Addresses of `bi/biz/... $r0` that are COMPUTED TAIL JUMPS (r0 reloaded
        # via lqa/lqr), not function returns -- see compute_bi_r0_jumps(). Empty
        # set => every `bi $r0` is a return (the prior behaviour).
        self.bi_r0_jump: set[int] = set()

    # ------------------------------------------------------------------ #
    def lift_function(self, insns: list[SPUInstruction],
                      start: int, end: int) -> LiftedFunction:
        func = LiftedFunction(name=f"{self.func_prefix}{start:08X}",
                              start_addr=start, end_addr=end)

        internal: set[int] = set()
        for insn in insns:
            if insn.addr < start or insn.addr >= end:
                continue
            tgt = self._branch_target(insn)
            if tgt is not None and start <= tgt < end:
                internal.add(tgt)

        last_insn = None
        for insn in insns:
            if insn.addr < start or insn.addr >= end:
                continue
            if insn.addr in internal:
                func.body_lines.append(f"loc_{insn.addr:08X}:")
            c = self._translate(insn, func)
            if c:
                if self.trace:
                    func.body_lines.append(f"    spu_trace_pc(ctx, 0x{insn.addr:X});")
                func.body_lines.append(f"    {c}")
                if self.trace and insn.mnemonic not in _NO_RT_WRITE and insn.mnemonic not in _LINK_OPS:
                    # Use the format-aware dest (RRR ops write bits 21-27, not raw&0x7F),
                    # else the trace mislabels shufb/selb/mpya/fma/fms/fnms writes and the
                    # RPCS3 register trace-diff sees false divergences. See _dest_reg().
                    rt_idx = _dest_reg(insn)
                    func.body_lines.append(f"    spu_trace_rt(ctx, {rt_idx});")
            last_insn = insn

        # Fall-through chaining: if the final instruction does NOT unconditionally
        # end the basic block (i.e. it's a normal op, a call brsl/bisl, or a
        # conditional branch whose not-taken path continues), execution proceeds
        # into the next sequential function. Emit a tail-call so the chain isn't
        # truncated (this was silently dropping execution mid-job).
        _TERMINATORS = {"br", "bra", "bi", "iret", "stop", "stopd"}
        if (last_insn is not None and last_insn.mnemonic not in _TERMINATORS
                and end in getattr(self, "func_starts", set())):
            # Fall-through is a TAIL transfer: route it through the trampoline
            # (g_spu_trampoline_fn + the enclosing SPU_DRAIN), NOT a nested host
            # call. A direct call grows the host stack one frame per fall-through,
            # which overflows on long straight-line runs -- catastrophic under
            # --seed-all (one function per instruction). Mirrors the cross-function
            # branch path and the design note in spu_context.h.
            func.body_lines.append(
                f"    {{ ctx->pc = 0x{end:X}; g_spu_trampoline_fn = "
                f"{self.func_prefix}{end:08X}; return; }}")

        self.functions.append(func)
        return func

    # ------------------------------------------------------------------ #
    def lift_region(self, insns: list[SPUInstruction], start: int, end: int,
                     pc_to_region: dict) -> LiftedFunction:
        """s41 SPU REGION LIFT (--regions): emit ONE region-spanning function
        covering [start, end) instead of one function per instruction. Mirrors
        lift_function()'s per-instruction translation (same _translate(), same
        rr_bin/etc tables) but with region-scoped control flow:

          * entry: `switch ((uint32_t)ctx->pc) { case <every pc>: goto
            loc_<pc>; ... default: <loud error>; }` -- preserves seed-all's
            enter-at-any-pc (design [REV] 2, review R8/R5).
          * every pc gets a `loc_<pc>:` label (not just branch targets) so
            in-region control transfer is always a plain `goto` -- the SAME
            label name _translate()/_uncond_branch() already emit for
            "internal" targets (func.start_addr <= tgt < func.end_addr), so
            no change was needed to the goto-emission side at all.
          * cross-region control transfers set ctx->pc THEN hand off (the
            [REV] 1 emitter invariant) -- see the pc_to_region-guarded
            branches inside _translate()/_uncond_branch().
        """
        func = LiftedFunction(name=f"spu_region_{start:08X}", start_addr=start, end_addr=end)
        region_insns = sorted((i for i in insns if start <= i.addr < end), key=lambda x: x.addr)

        # Entry switch: case every registered pc in the region (dense ->
        # MSVC jump table) + a LOUD default (design [REV] 2, review R8). A pc
        # that reaches default is a genuinely corrupted resume -- every real
        # instruction start in the region is cased below.
        func.body_lines.append("switch ((uint32_t)ctx->pc) {")
        for insn in region_insns:
            func.body_lines.append(f"case 0x{insn.addr:08X}u: goto loc_{insn.addr:08X};")
        func.body_lines.append("default:")
        func.body_lines.append(
            f'    fprintf(stderr, "[spu-region] pc=0x%05X not a case in '
            f'spu_region_{start:08X} (image=%d)\\n", ctx->pc, ctx->image_id); '
            f'fflush(stderr);')
        func.body_lines.append("    spu_halt(ctx, SPU_STATUS_STOPPED_BY_HALT);")
        func.body_lines.append("    return;")
        func.body_lines.append("}")

        last_insn = None
        for insn in region_insns:
            func.body_lines.append(f"loc_{insn.addr:08X}:")
            c = self._translate(insn, func, pc_to_region)
            if c:
                func.body_lines.append(f"    {c}")
            last_insn = insn

        # Fall-through: regions tile the image contiguously by construction,
        # so `end` is either the next region's start (a real case in THAT
        # region's switch) or past the last instruction of the image. Same
        # tail-transfer shape as lift_function's chaining, generalized to
        # regions (and already pc-materialized, matching [REV] 1).
        _TERMINATORS = {"br", "bra", "bi", "iret", "stop", "stopd"}
        if (last_insn is not None and last_insn.mnemonic not in _TERMINATORS
                and end in pc_to_region):
            func.body_lines.append(
                f"    {{ ctx->pc = 0x{end:X}u; g_spu_trampoline_fn = "
                f"spu_region_{end:08X}; return; }}")

        self.functions.append(func)
        return func

    @staticmethod
    def _branch_target(insn: SPUInstruction):
        mn = insn.mnemonic
        ops = _ops(insn.operands)
        tok = None
        if mn in ("br", "bra") and ops:
            tok = ops[0]
        elif mn in ("brsl", "brasl") and ops:
            # The s15 disasm fix (T9) added the link register to brsl/brasl
            # operands ("brsl $r0, 0x5488"); the target is the LAST operand.
            # ops[0] was correct only for the pre-fix format and silently
            # returned None afterwards, lifting EVERY brsl call as a no-op
            # (caught 2026-07-08: jobB's 18 dropped calls = the round-1
            # early-exit). ops[-1] handles both formats.
            tok = ops[-1]
        elif mn in _COND_BR and ops:
            tok = ops[-1]
        if tok and tok.startswith("0x"):
            try:
                return int(tok, 16)
            except ValueError:
                return None
        return None

    # ------------------------------------------------------------------ #
    def _translate(self, insn: SPUInstruction, func: LiftedFunction,
                    pc_to_region: dict = None) -> str:
        # pc_to_region is None on every existing (legacy/DIAG) call site --
        # lift_function() never passes it -- so every branch below guarded by
        # `pc_to_region is not None` is DEAD in DIAG mode and the emitted text
        # is byte-identical to before this parameter existed. Only lift_region()
        # (s41 --regions) passes a real dict, activating the pc-materialization
        # invariant ([REV] 1/4: ctx->pc must be set before every trampoline set
        # or region call -- see scratch/s41_spu_region_lift_design.md).
        mn = insn.mnemonic
        ops = _ops(insn.operands)
        addr = insn.addr

        def rt(): return _reg(ops[0])
        def ra(): return _reg(ops[1])
        def rb(): return _reg(ops[2])
        def g(i): return f"ctx->gpr[{i}]"

        # ---- nop / sync / stop ----
        if mn in ("nop", "lnop"):
            return "/* nop */;"
        if mn in ("sync", "dsync", "syncc"):
            # SPU ISA v1.2 §13 + the 'Synchronize (Data)' pages: these order
            # earlier LS/channel accesses before later ones and publish LS for
            # external observers (Table 13-6 = our exact PPU-thread->SPU
            # handoff). Formerly a no-op -- the SPU twin of LESSONS #11d.
            # syncc's extra duty (channel-written execution state) is covered
            # structurally: our channel ops are locked host calls.
            return "spu_arch_fence();"
        if mn == "fscrwr":
            # Write FP status/control register -- we don't model FPSCR (rounding
            # mode / exception flags), so this is a no-op (matches spu_fscrrd=0).
            return "/* fscrwr (FPSCR not modelled) */;"
        if mn == "stop":
            # F18: capture the 14-bit stop code (disasm emits it as ops[0]) so the
            # driver can dispatch the stop-and-signal protocol (thread/group exit).
            # [REV] 4/5: materialize pc before a stop in region mode (a stop/halt
            # site) -- no-op in legacy (pc_set == "").
            pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
            return f"{pc_set}ctx->stop_code = {_imm(ops[0])}; ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;"

        # ---- immediate loaders ----
        if mn == "il":
            return f"{g(rt())} = spu_il({_imm(ops[1])});"
        if mn == "ila":
            return f"{g(rt())} = spu_ila({_imm(ops[1])});"
        if mn == "ilh":
            return f"{g(rt())} = spu_ilh({_imm(ops[1])});"
        if mn == "ilhu":
            return f"{g(rt())} = spu_ilhu({_imm(ops[1])});"
        if mn == "iohl":
            return f"{g(rt())} = spu_iohl({g(rt())}, {_imm(ops[1])});"
        if mn == "fsmbi":
            return f"{g(rt())} = spu_fsmbi({_imm(ops[1])});"

        # addx / bgx: read rt as carry-in (and write rt)
        if mn == "addx":
            return f"{g(rt())} = spu_addx({g(ra())}, {g(rb())}, {g(rt())});"
        if mn == "bgx":
            return f"{g(rt())} = spu_bgx({g(ra())}, {g(rb())}, {g(rt())});"

        # Halt-on-condition + stopd: pure stop semantics in recompiled code;
        # we just continue execution (no host halt path for these yet).
        if mn in ("hgti", "hlgti", "heqi", "hgt", "hlgt", "heq"):
            return f"/* {mn}: halt-on-condition (no-op in recomp) */;"
        if mn == "stopd":
            # stopd's stop code is architecturally fixed at 0x3FFF (CBEA p97).
            pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
            return f"{pc_set}ctx->stop_code = 0x3FFF; ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;"

        # ---- integer arithmetic (register) ----
        rr_bin = {
            "a": "spu_a", "sf": "spu_sf", "ah": "spu_ah", "sfh": "spu_sfh",
            "and": "spu_and", "or": "spu_or", "xor": "spu_xor",
            "nand": "spu_nand", "nor": "spu_nor", "andc": "spu_andc", "orc": "spu_orc",
            "ceq": "spu_ceq", "ceqh": "spu_ceqh", "ceqb": "spu_ceqb",
            "cgt": "spu_cgt", "cgth": "spu_cgth", "cgtb": "spu_cgtb",
            "clgt": "spu_clgt", "clgth": "spu_clgth", "clgtb": "spu_clgtb",
            "mpy": "spu_mpy", "mpyu": "spu_mpyu",
            "mpyh": "spu_mpyh", "mpyhh": "spu_mpyhh", "mpys": "spu_mpys",
            "fa": "spu_fa", "fs": "spu_fs", "fm": "spu_fm",
            "fi": "spu_fi",   # floating interpolate (reciprocal refine)
            "fceq": "spu_fceq", "fcgt": "spu_fcgt",
            "fcmeq": "spu_fcmeq", "fcmgt": "spu_fcmgt",
            # double-precision (2 doubles/reg) + double compares
            "dfa": "spu_dfa", "dfs": "spu_dfs", "dfm": "spu_dfm",
            "dfceq": "spu_dfceq", "dfcmeq": "spu_dfcmeq",
            "dfcgt": "spu_dfcgt", "dfcmgt": "spu_dfcmgt",
            "mpyhhu": "spu_mpyhhu",
            "eqv": "spu_eqv", "absdb": "spu_absdb", "avgb": "spu_avgb",
            "cg": "spu_cg", "bg": "spu_bg",
            "sumb": "spu_sumb",   # sum bytes of each word into the two halfwords
            # Phase 2: register-variable shifts/rotates
            "shl": "spu_shl", "shlh": "spu_shlh",
            "rot": "spu_rot", "roth": "spu_roth",
            "shlqbi": "spu_shlqbi",  "rotqbi": "spu_rotqbi",
            "shlqby": "spu_shlqby",  "rotqby": "spu_rotqby",
            "shlqbybi": "spu_shlqbybi", "rotqbybi": "spu_rotqbybi",
            # Phase 3: rotate-and-mask (register-variable)
            "rotm": "spu_rotm", "rotma": "spu_rotma",
            "rothm": "spu_rothm", "rothma": "spu_rothma",
            # ISA v1.2 p145: the assembler mnemonic is rotmah (was only mapped
            # under the rothma alias -- register form fell to the TODO
            # catch-all; caught RED by test_spu_lift.py 2026-07-03)
            "rotmah": "spu_rothma",
            "rotqmbi": "spu_rotqmbi", "rotqmby": "spu_rotqmby",
            "rotqmbybi": "spu_rotqmbybi",
            # Phase 3: indexed constant generators (insertion masks)
            "cbx": "spu_cbx", "chx": "spu_chx",
            "cwx": "spu_cwx", "cdx": "spu_cdx",
        }
        if mn in rr_bin:
            return f"{g(rt())} = {rr_bin[mn]}({g(ra())}, {g(rb())});"

        # ---- unary (register) ----
        rr_un = {
            "clz": "spu_clz", "cntb": "spu_cntb",
            "fscrrd": "spu_fscrrd",
            "gb": "spu_gb", "gbh": "spu_gbh", "gbb": "spu_gbb",
            "frsqest": "spu_frsqest", "frest": "spu_frest",
            "fesd": "spu_fesd", "frds": "spu_frds",   # single<->double convert
            # Phase 3
            "xsbh": "spu_xsbh", "xshw": "spu_xshw", "xswd": "spu_xswd",
            "orx": "spu_orx",
            "fsm": "spu_fsm", "fsmh": "spu_fsmh", "fsmb": "spu_fsmb",
            "mfspr": "spu_mfspr",
        }
        if mn in rr_un:
            return f"{g(rt())} = {rr_un[mn]}({g(ra())});"

        # ---- move register (or rt,ra,ra) handled by generic 'or' above ----

        # ---- arithmetic / logical / compare immediate ----
        ri_imm = {
            "ai": "spu_ai", "ahi": "spu_ahi", "sfi": "spu_sfi", "sfhi": "spu_sfhi",
            "andi": "spu_andi", "ori": "spu_ori", "xori": "spu_xori",
            "ceqi": "spu_ceqi", "cgti": "spu_cgti", "clgti": "spu_clgti",
            "ceqbi": "spu_ceqbi", "ceqhi": "spu_ceqhi",
            "clgtbi": "spu_clgtbi", "clgthi": "spu_clgthi",
            "cgthi": "spu_cgthi", "cgtbi": "spu_cgtbi",
            "mpyi": "spu_mpyi", "mpyui": "spu_mpyui",
            # Phase 3: halfword/byte immediate logic
            "andhi": "spu_andhi", "andbi": "spu_andbi",
            "orhi":  "spu_orhi",  "orbi":  "spu_orbi",
            "xorhi": "spu_xorhi", "xorbi": "spu_xorbi",
            "dftsv": "spu_dftsv",
            # RI8 float<->int conversions with scale (i8 in ops[2])
            "cflts": "spu_cflts", "cfltu": "spu_cfltu",
            "csflt": "spu_csflt", "cuflt": "spu_cuflt",
        }
        if mn in ri_imm:
            return f"{g(rt())} = {ri_imm[mn]}({g(ra())}, {_imm(ops[2])});"

        # ---- shift / rotate immediate ----
        sh_imm = {
            "shli": "spu_shli", "shlhi": "spu_shlhi",
            "roti": "spu_roti", "rothi": "spu_rothi",
            "rotmi": "spu_rotmi", "rotmai": "spu_rotmai", "rotmhi": "spu_rotmhi",
            "rotmahi": "spu_rotmahi",
            "shlqbyi": "spu_shlqbyi", "rotqbyi": "spu_rotqbyi",
            "shlqbii": "spu_shlqbii", "rotqbii": "spu_rotqbii",
            # Phase 3: rotate-and-mask immediate + d-form constant generators
            "rothmi": "spu_rothmi",
            "rotqmbii": "spu_rotqmbii", "rotqmbyi": "spu_rotqmbyi",
            "cbd": "spu_cbd", "chd": "spu_chd",
            "cwd": "spu_cwd", "cdd": "spu_cdd",
        }
        if mn in sh_imm:
            # Disassembler quirk: the quad shift/rotate RI7 forms (shlqbyi,
            # rotqbyi, shlqbii, rotqbii) are matched against SPU_RR first and
            # therefore emitted with 3-register operands, with the i7 bits
            # disguised as "$rN". The register index IS the immediate value,
            # so we strip the "$r" and use the digits literally.
            tok = ops[2]
            if tok.startswith("$r"):
                tok = tok[2:]
            else:
                tok = _imm(tok)
            return f"{g(rt())} = {sh_imm[mn]}({g(ra())}, {tok});"

        # ---- select / shuffle (RRR: rt, ra, rb, rc) ----
        if mn == "selb":
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_selb({g(ra())}, {g(rb())}, {g(rc)});"
        if mn == "shufb":
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_shufb({g(ra())}, {g(rb())}, {g(rc)});"
        if mn in ("fma", "fms", "fnms", "mpya"):
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rc)});"
        # sfx: extended subtract — RT is also a source (carry-in = low bit of old RT).
        if mn == "sfx":
            return f"{g(rt())} = spu_sfx({g(ra())}, {g(rb())}, {g(rt())});"
        # cgx: extended carry-generate — RT is also a source (carry-in = low bit).
        if mn == "cgx":
            return f"{g(rt())} = spu_cgx({g(ra())}, {g(rb())}, {g(rt())});"
        # double FMA (dfma/dfms/dfnms/dfnma): 3-register, RT is the accumulator (c).
        if mn in ("dfma", "dfms", "dfnms", "dfnma"):
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rt())});"
        # mpyhha/mpyhhau: high-half multiply accumulated into RT (3-register).
        if mn in ("mpyhha", "mpyhhau"):
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rt())});"

        # ---- quadword loads / stores ----
        if mn == "lqd":
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"{g(rt())} = spu_ls_read128(ctx, {g(base)}._u32[0] + {disp});"
        if mn == "stqd":
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"spu_ls_write128(ctx, {g(base)}._u32[0] + {disp}, {g(rt())});"
        if mn in ("lqa", "lqr"):
            return f"{g(rt())} = spu_ls_read128(ctx, {_imm(ops[1])});"
        if mn in ("stqa", "stqr"):
            return f"spu_ls_write128(ctx, {_imm(ops[1])}, {g(rt())});"
        if mn == "lqx":
            return f"{g(rt())} = spu_ls_read128(ctx, {g(ra())}._u32[0] + {g(rb())}._u32[0]);"
        if mn == "stqx":
            return f"spu_ls_write128(ctx, {g(ra())}._u32[0] + {g(rb())}._u32[0], {g(rt())});"

        # ---- channel ops ----
        # [REV] 4/5: materialize ctx->pc before every channel call in region
        # mode -- spu_ch_wait's [ch-block]/[ch-wait] diagnostics log ctx->pc,
        # and would otherwise read a stale/region-granular pc (spu_channels.c
        # ~1092/1116). No-op in legacy (pc_set == "").
        if mn == "rdch":
            pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
            return f"{pc_set}{g(rt())} = spu_rdch(ctx, {_chan(ops[1])});"
        if mn == "rchcnt":
            # CBEA: the count lands in the PREFERRED word, remaining slots ZERO
            # (splatting it is the spu_link bug class; RPCS3 = v128::from32r).
            pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
            return f"{pc_set}{g(rt())} = spu_pref_u32(spu_rchcnt(ctx, {_chan(ops[1])}));"
        if mn == "wrch":
            # operands: channel, $rt
            pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
            return f"{pc_set}spu_wrch(ctx, {_chan(ops[0])}, {g(_reg(ops[1]))});"

        # ---- branches ----
        if mn in ("br", "bra"):
            tgt = self._branch_target(insn)
            # SELF-LOOP TRAP: `br .` (target == this instruction) is an infinite
            # hang on real SPU -- a deliberate trap, no forward progress. Emitting
            # `goto loc_self` busy-spins the host thread forever; stop the SPU
            # instead (same halt path the lifter emits for a `stop` instruction).
            if tgt == addr:
                pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
                return f"{pc_set}ctx->status = SPU_STATUS_STOPPED_BY_HALT; return;"
            return self._uncond_branch(tgt, func, pc_to_region)
        if mn in ("brsl", "brasl"):
            # The disassembler drops the link register from brsl operands, so
            # recover it from the raw encoding (rt = bits 25-31 = raw & 0x7F).
            link_rt = insn.raw & 0x7F
            tgt = self._branch_target(insn)
            link = f"{g(link_rt)} = spu_link(0x{addr + 4:X});"
            if self.trace:
                link += f" spu_trace_rt(ctx, {link_rt});"   # log the link AT the call PC
            # SELF-LOOP TRAP: `brsl rX, .` (target == this instruction) is an
            # infinite loop on real SPU (re-sets the link each pass, never
            # advances) -- a trap, NOT a call. Emitting a host call recurses
            # forever -> host stack overflow -> segfault (observed crashing the
            # boot in cri_audio_00023C58). Set the link, then stop the SPU (same
            # halt path the lifter emits for a `stop` instruction).
            if tgt == addr:
                pc_set = f"ctx->pc = 0x{addr:X}u; " if pc_to_region is not None else ""
                return f"{link} {pc_set}ctx->status = SPU_STATUS_STOPPED_BY_HALT; return;"
            # PC-GETTER IDIOM: `brsl rX, .+4` (target == next instruction) just
            # loads PC+4 into rX for PC-relative addressing / computed jump tables;
            # it is NOT a real call. Emitting a host call here imbalances the C
            # call/return nesting -- the "callee" falls through into the rest of
            # the function and a later `bi $r0` return unwinds to this brsl's frame
            # instead of the real caller (observed: SPURS taskset LoadElf's return
            # landed back inside its own clear loop, running it with a stale count).
            # Treat it as: set the link, then fall through to addr+4.
            if tgt == addr + 4:
                return f"{link} {self._uncond_branch(addr + 4, func, pc_to_region)}"
            if tgt is not None:
                self.call_targets.add(tgt)
                # Call, then drain any tail-call the callee left pending so
                # cross-function loops run iteratively (constant host stack).
                # host_depth brackets the nested host call so SPU_RET can tell
                # a live lifted frame from one consumed by a resume/restack
                # unwind (see SPU_RET in spu_context.h). The image_id local +
                # spu_img_restore = the restore-on-host-return bracket of the
                # adopt-on-serve image model (spu_context.h): an image adopted
                # inside the callee (dispatcher serve, foreign adoption, drain
                # tail-chain hops) is scoped to the call and cannot leak into
                # this function's continuation.
                #
                # [REV] 3: under regions, the callee is no longer a per-address
                # symbol -- it's the REGION that CONTAINS tgt, entered via its
                # `switch (ctx->pc)`, so ctx->pc = tgt MUST be set before the
                # call (design brief §3 direct-call idiom). Legacy (pc_to_region
                # is None) is unaffected: the callee ignores ctx->pc and this
                # produces byte-identical text to before.
                if pc_to_region is not None:
                    owner = pc_to_region.get(tgt)
                    pc_set = f"ctx->pc = 0x{tgt:X}u; "
                    if owner is not None:
                        callee = f"spu_region_{owner:08X}(ctx);"
                    else:
                        # Not found in this image's region map (should not
                        # happen for a fully-covered single-image lift) --
                        # fall back to the global indirect dispatcher instead
                        # of guessing an unlinkable symbol name.
                        self.region_fallback_hits += 1
                        callee = "spu_indirect_branch(ctx);"
                else:
                    pc_set = ""
                    callee = f"{self.func_prefix}{tgt:08X}(ctx);"
                return (f"{link} {pc_set}{{ int32_t _si = (int32_t)ctx->image_id; "
                        f"ctx->host_depth++; "
                        f"{callee} SPU_DRAIN(ctx); "
                        f"ctx->host_depth--; spu_img_restore(ctx, _si); }}")
            self.unresolved_calls.append(addr)
            return f"{link} /* TODO spu: brsl unresolved target */;"
        if mn in _COND_BR:
            tgt = self._branch_target(insn)
            cond = self._cond(mn, _reg(ops[0]))
            if tgt is None:
                return f"/* TODO spu: {mn} {insn.operands} */;"
            if func.start_addr <= tgt < func.end_addr:
                return f"if ({cond}) goto loc_{tgt:08X};"
            self.branch_targets.add(tgt)
            # Cross-function conditional branch = conditional tail call: hand
            # the target to the trampoline and unwind (see SPU_DRAIN).
            # [REV] 1: under regions the trampoline target's entry switch
            # CONSUMES ctx->pc, so it must be set before the trampoline fn
            # (this was the review's CONFIRMED HOLE -- "exactly as today" was
            # false for this exact site). Legacy (pc_to_region is None) is
            # unaffected -- byte-identical to before.
            if pc_to_region is not None:
                owner = pc_to_region.get(tgt)
                pc_set = f"ctx->pc = 0x{tgt:X}u; "
                if owner is not None:
                    tgt_sym = f"spu_region_{owner:08X}"
                else:
                    self.region_fallback_hits += 1
                    tgt_sym = "spu_indirect_branch"
            else:
                pc_set = ""
                tgt_sym = f"{self.func_prefix}{tgt:08X}"
            return (f"if ({cond}) {{ {pc_set}g_spu_trampoline_fn = {tgt_sym}; "
                    f"return; }}")
        # For bi/bisl the disassembler emits only "$rA" (ops[0] = target reg).
        if mn in ("bi",):
            tgt_reg = _reg(ops[0])
            # SPU ABI: $r0 is the link register. `bi $r0` is the standard
            # function return — SPU_RET keeps the host return while a matching
            # lifted brsl/bisl frame is live (ctx->host_depth > 0) and falls
            # back to dispatching to r0 when none is (a cross-context task
            # resume or the restack unwind consumed the caller's host frame;
            # a bare `return` there hands control to the dispatch drain and
            # kills the SPU's thread of control — the LS 0x20A40 codec death,
            # 2026-07-03). EXCEPTION: when r0 was reloaded from memory
            # (lqa/lqr) it is a COMPUTED TAIL JUMP (e.g. the SPURS task launch
            # `lqa $r0,savedContextLr; bi $r0`), flagged by
            # compute_bi_r0_jumps() — emit the unconditional indirect dispatch.
            if tgt_reg == "0" and addr not in self.bi_r0_jump:
                return "SPU_RET(ctx);"
            # Indirect tail branch: set pc and trampoline to the dispatcher,
            # then unwind so an enclosing SPU_DRAIN re-enters (no nesting).
            return (f"ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"g_spu_trampoline_fn = spu_indirect_branch; return;")
        # iret: interrupt return -> branch to the saved interrupt PC (SRR0).
        if mn == "iret":
            return ("ctx->pc = ctx->srr0; "
                    "g_spu_trampoline_fn = spu_indirect_branch; return;")
        if mn in ("bisl",):
            link_rt = insn.raw & 0x7F
            # Same interface break as brsl: the disasm fix added the link
            # register to bisl operand text ("bisl $r0, $r11"), so the TARGET
            # register moved to the LAST operand. ops[0] was correct only for
            # the pre-fix single-operand format; post-fix it grabbed the LINK
            # register, so the emitted call dispatched to link (= addr+4) and
            # the callee was silently skipped. ops[-1] handles both formats.
            tgt_reg = _reg(ops[-1])
            # Indirect call: dispatch, then drain the callee's tail-calls.
            # host_depth brackets the nested call (see the brsl emission);
            # the image bracket scopes any adopt-on-serve to the call.
            tr = f" spu_trace_rt(ctx, {link_rt});" if self.trace else ""
            return (f"{g(link_rt)} = spu_link(0x{addr + 4:X});{tr} "
                    f"{{ int32_t _si = (int32_t)ctx->image_id; "
                    f"ctx->pc = {g(tgt_reg)}._u32[0]; ctx->host_depth++; "
                    f"spu_indirect_branch(ctx); SPU_DRAIN(ctx); "
                    f"ctx->host_depth--; spu_img_restore(ctx, _si); }}")
        # bisled: set link, branch to RA only if an external event is pending.
        if mn in ("bisled",):
            link_rt = insn.raw & 0x7F
            tgt_reg = _reg(ops[-1])   # last operand = target (see bisl above)
            tr = f" spu_trace_rt(ctx, {link_rt});" if self.trace else ""
            return (f"{g(link_rt)} = spu_link(0x{addr + 4:X});{tr} "
                    f"if ((ctx->event_status & ctx->event_mask) != 0) {{ "
                    f"ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"g_spu_trampoline_fn = spu_indirect_branch; return; }}")
        # biz/binz/bihz/bihnz: ops[0] = condition reg, ops[1] = target reg.
        if mn in ("biz", "binz", "bihz", "bihnz"):
            cond = self._cond(mn[1:], _reg(ops[0]))   # strip leading 'b' -> iz/inz...
            tgt_reg = _reg(ops[1])
            # $r0 is the link register: a conditional branch to it is a
            # conditional function return — SPU_RET (mirrors the `bi $r0` case
            # above: host return while a lifted call frame is live, dispatch
            # to r0 when the frame was consumed by a resume/restack unwind).
            if tgt_reg == "0" and addr not in self.bi_r0_jump:
                return f"if ({cond}) SPU_RET(ctx);"
            return (f"if ({cond}) {{ ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"g_spu_trampoline_fn = spu_indirect_branch; return; }}")

        # hint-for-branch: pure performance hint, safe to drop
        if mn in ("hbr", "hbra", "hbrr"):
            return "/* branch hint (ignored) */;"
        # mtspr: SPU special-purpose-register writes are ignored (RPCS3: SPRs unused)
        if mn == "mtspr":
            return "/* mtspr: SPR write ignored */;"

        # ---- fallthrough: unsupported ----
        self.unsupported[mn] = self.unsupported.get(mn, 0) + 1
        return f"/* TODO spu: {mn} {insn.operands} */;"

    # ------------------------------------------------------------------ #
    def _cond(self, mn: str, reg: str) -> str:
        """Condition expression on preferred slot for conditional branches."""
        word = f"ctx->gpr[{reg}]._u32[0]"
        # brhz/brhnz test the rightmost 16 bits of the preferred word (SPU bytes
        # 2-3). Our u128 stores word values, so on a little-endian host the low
        # halfword of _u32[0] is _u16[0] (bytes 2-3 in SPU big-endian order);
        # _u16[1] is the LEFT (high) halfword. Use _u16[0]. (Was _u16[1] -- a
        # byte-order bug that made every halfword conditional branch test the
        # wrong 16 bits; e.g. the SPURS service's ActivateWorkload trigger.)
        half = f"ctx->gpr[{reg}]._u16[0]"   # preferred halfword = low 16 bits of word 0
        table = {
            "brz": f"{word} == 0",      "brnz": f"{word} != 0",
            "brhz": f"{half} == 0",     "brhnz": f"{half} != 0",
            "iz": f"{word} == 0",       "inz": f"{word} != 0",
            "ihz": f"{half} == 0",      "ihnz": f"{half} != 0",
        }
        return table.get(mn, f"{word} != 0")

    def _uncond_branch(self, tgt, func: LiftedFunction, pc_to_region: dict = None) -> str:
        if tgt is None:
            return "/* TODO spu: unresolved branch */;"
        if func.start_addr <= tgt < func.end_addr:
            return f"goto loc_{tgt:08X};"
        self.branch_targets.add(tgt)
        # Cross-function unconditional branch = tail call: trampoline + unwind.
        # [REV] 1: same CONFIRMED HOLE as the conditional-branch case above --
        # ctx->pc must be set before the trampoline fn in region mode. Legacy
        # (pc_to_region is None) is unaffected -- byte-identical to before.
        if pc_to_region is not None:
            owner = pc_to_region.get(tgt)
            pc_set = f"ctx->pc = 0x{tgt:X}u; "
            if owner is not None:
                tgt_sym = f"spu_region_{owner:08X}"
            else:
                self.region_fallback_hits += 1
                tgt_sym = "spu_indirect_branch"
        else:
            pc_set = ""
            tgt_sym = f"{self.func_prefix}{tgt:08X}"
        return f"{{ {pc_set}g_spu_trampoline_fn = {tgt_sym}; return; }}"

    # ------------------------------------------------------------------ #
    def emit_header(self) -> str:
        lines = [HEADER_PREAMBLE, ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx);")
        defined = {f.start_addr for f in self.functions}
        for t in sorted(self.call_targets | self.branch_targets):
            if t not in defined:
                lines.append(f"void {self.func_prefix}{t:08X}(spu_context* ctx); /* external */")
        lines.append("")
        lines.append("/* Runtime glue (runtime/spu/spu_channels.c) */")
        lines.append("void spu_register_function(uint32_t addr, void (*fn)(spu_context*));")
        lines.append("/* Call once at init to register this image's functions for")
        lines.append(" * indirect-branch dispatch (spu_indirect_branch). */")
        lines.append(f"void {self.register_name}(void);")
        lines.append("")
        return "\n".join(lines)

    def emit_source(self) -> str:
        lines = [SOURCE_PREAMBLE.replace("{header_name}", self.header_name), ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx) {{")
            for b in f.body_lines:
                lines.append(b if b.endswith(":") else f"    {b}")
            lines.append("}")
            lines.append("")

        # Stubs for cross-function branch/call targets the function-boundary
        # detector did not promote to standalone functions. The lifter emits
        # `spu_func_<tgt>(ctx)` calls eagerly, so the linker needs a symbol;
        # at runtime we route through spu_indirect_branch which either lands
        # on a registered mid-function entry (if one was emitted) or halts
        # cleanly with a "PC X not registered" diagnostic.
        defined = {f.start_addr for f in self.functions}
        externs = sorted((self.call_targets | self.branch_targets) - defined)
        if externs:
            lines.append("/* Indirect-dispatch stubs for cross-function targets the")
            lines.append(" * function detector did not seed (typically conditional")
            lines.append(" * branches that escape a function's range). */")
            for t in externs:
                lines.append(f"void {self.func_prefix}{t:08X}(spu_context* ctx) {{")
                lines.append(f"    ctx->pc = 0x{t:X}u; spu_indirect_branch(ctx);")
                lines.append("}")
            lines.append("")

        lines.append("/* Function table */")
        lines.append("typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;")
        lines.append("static const spu_func_entry spu_function_table[] = {")
        for f in self.functions:
            lines.append(f'    {{ 0x{f.start_addr:08X}u, {f.name}, "{f.name}" }},')
        lines.append("    { 0, NULL, NULL }")
        lines.append("};")
        lines.append("")
        lines.append(f"void {self.register_name}(void) {{")
        lines.append("    for (const spu_func_entry* e = spu_function_table; e->func; ++e)")
        lines.append("        spu_register_function(e->addr, e->func);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    # s41 SPU REGION LIFT (--regions) emission. Separate from emit_header/
    # emit_source (rather than parametrizing them) so the DIAG path above is
    # untouched code, not code with a new branch threaded through it --
    # the no-regression proof is "the DIAG emitter wasn't edited," not "the
    # edited DIAG emitter still produces the same bytes."
    def emit_region_header(self) -> str:
        lines = [HEADER_PREAMBLE, ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx);")
        lines.append("")
        lines.append("/* Runtime glue (runtime/spu/spu_channels.c) */")
        lines.append("void spu_register_function(uint32_t addr, void (*fn)(spu_context*));")
        lines.append("/* Call once at init to register this image's functions for")
        lines.append(" * indirect-branch dispatch (spu_indirect_branch). */")
        lines.append(f"void {self.register_name}(void);")
        lines.append("")
        return "\n".join(lines)

    def emit_region_source(self, pc_to_region: dict) -> str:
        lines = [SOURCE_PREAMBLE.replace("{header_name}", self.header_name), ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx) {{")
            for b in f.body_lines:
                lines.append(b if b.endswith(":") else f"    {b}")
            lines.append("}")
            lines.append("")

        # Per-pc registration table: EVERY instruction address in the image
        # maps to the region function that CONTAINS it (design mechanic 3/5;
        # review (g)) -- same table shape as the per-instruction seed-all
        # build, just far fewer distinct function pointers behind it.
        lines.append("/* Function table -- every pc maps to its containing region (s41 region lift) */")
        lines.append("typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;")
        lines.append("static const spu_func_entry spu_function_table[] = {")
        for addr in sorted(pc_to_region.keys()):
            owner = pc_to_region[addr]
            lines.append(f'    {{ 0x{addr:08X}u, spu_region_{owner:08X}, "spu_region_{owner:08X}" }},')
        lines.append("    { 0, NULL, NULL }")
        lines.append("};")
        lines.append("")
        lines.append(f"void {self.register_name}(void) {{")
        lines.append("    for (const spu_func_entry* e = spu_function_table; e->func; ++e)")
        lines.append("        spu_register_function(e->addr, e->func);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description="SPU to C lifter for ps3recomp")
    p.add_argument("input", nargs="?", default=None,
                   help="Raw SPU binary (local-store image) or segment. "
                        "Omit if --auto-functions is set.")
    p.add_argument("--output", "-o", default=".", help="Output directory")
    p.add_argument("--header-name", default="spu_recomp.h")
    p.add_argument("--source-name", default="spu_recomp.c")
    p.add_argument("--register-name", default="spu_recomp_register",
                   help="Name of the emitted global registration function "
                        "(override to link multiple SPU images together).")
    p.add_argument("--func-prefix", default="spu_func_",
                   help="C symbol prefix for emitted functions (override for "
                        "images that load to OVERLAPPING LS addresses, e.g. the "
                        "SPURS service vs a taskset policy both at LS 0xA00, so "
                        "their spu_func_<addr> symbols don't collide at link).")
    p.add_argument("--base", type=lambda x: int(x, 0), default=0,
                   help="Base local-store address")
    p.add_argument("--offset", type=lambda x: int(x, 0), default=0)
    p.add_argument("--length", type=lambda x: int(x, 0), default=0)
    p.add_argument("--functions", metavar="FILE",
                   help="JSON list [{\"start\":addr,\"end\":addr}, ...]")
    p.add_argument("--auto-functions", metavar="ELF",
                   help="Auto-detect function boundaries from the given SPU "
                        "ELF using find_spu_functions.py (entry + brsl/brasl "
                        "targets + STT_FUNC symbols). When set, .text is "
                        "read from this ELF and the positional <input> arg "
                        "is ignored.")
    p.add_argument("--trace", action="store_true",
                   help="Emit spu_trace_pc/spu_trace_rt around each instruction "
                        "for §3 diff-vs-RPCS3 validation. Output goes to stderr "
                        "unless spu_trace_init(path) is called by the harness.")
    p.add_argument("--seed-all", action="store_true",
                   help="Treat EVERY 4-aligned instruction as its own function "
                        "entry (the lifter splits anywhere and chains fall-through "
                        "with tail calls, so semantics are preserved). Use for "
                        "modules with COMPUTED-branch dispatch whose targets cannot "
                        "be resolved statically -- e.g. the SPURS taskset policy mixes "
                        "Duff's-device memsets with convergent error-code jump tables, "
                        "so an indirect branch can land on essentially any mid-function "
                        "PC. With this, every such PC is a registered entry and the "
                        "dispatcher never halts 'unknown branch'. Over-seeds heavily "
                        "(one C function per instruction) -- only for small, "
                        "perf-noncritical images like the policy module.")
    p.add_argument("--regions", action="store_true",
                   help="s41 SPU REGION LIFT: emit multi-instruction REGION "
                        "functions (internal goto/labels, trampoline only at "
                        "region boundaries) instead of one C function per "
                        "instruction -- the FAST build path. See "
                        "scratch/s41_spu_region_lift_design.md. Off by default; "
                        "--seed-all is ignored when this is set (regions "
                        "supersede it -- every pc is still registered, just "
                        "grouped behind far fewer functions). Refuses --trace "
                        "(DIAG covers per-instruction tracing).")
    p.add_argument("--region-cap", type=int, default=256,
                   help="Max instructions per region before a forced cut "
                        "(design [REV] 7 / review R4: start at 256-512, raise "
                        "only after measuring /O2 compile time). Only used "
                        "with --regions.")
    args = p.parse_args()

    if args.regions and args.trace:
        print("ERROR: --trace is not supported with --regions (DIAG is the "
              "per-instruction trace substrate; use a non-region lift for "
              "tracediff.py work). See design [REV] 7 / review R7.",
              file=sys.stderr)
        sys.exit(1)

    if args.auto_functions:
        from find_spu_functions import detect_functions, parse_elf, pick_text
        with open(args.auto_functions, "rb") as f:
            elf_buf = f.read()
        funcs, (text_off, base, size) = detect_functions(elf_buf)
        data = elf_buf[text_off:text_off + size]
        if args.base != 0:
            base = args.base  # caller override
        bounds = funcs
    else:
        with open(args.input, "rb") as f:
            data = f.read()
        data = data[args.offset:]
        if args.length:
            data = data[:args.length]
        base = args.base

        if args.functions:
            with open(args.functions) as f:
                flist = json.load(f)
            bounds = [(int(str(e["start"]), 0), int(str(e["end"]), 0))
                      for e in flist]
        else:
            # No boundary info: treat the whole image as one function.
            bounds = [(base, base + len(data))]

    # The LOGICAL function bounds (before --seed-all shatters them into one
    # function per instruction). Used for the bi-$r0 computed-jump analysis,
    # which must see a whole function to find r0's nearest writer.
    logical_bounds = list(bounds)

    if args.seed_all:
        # Every 4-aligned instruction becomes its own function entry. SPU
        # instructions are fixed 4 bytes, so this covers every possible
        # computed-branch landing site; the lifter chains the fall-through.
        n = len(data) & ~3
        bounds = [(base + i, base + i + 4) for i in range(0, n, 4)]

    insns = disassemble_spu(data, base)

    region_starts = None
    if args.regions:
        if args.auto_functions:
            # DELIBERATELY narrower than `logical_bounds` here: find_spu_functions'
            # detected-function list also seeds every plain branch target,
            # jump-table word, ila-immediate, and computed-branch landing site
            # (all needed for --seed-all's enter-at-any-pc coverage). Forcing a
            # region split at EVERY one of those defeats the region model's
            # whole purpose -- measured: 527 regions for gs_task (many
            # singletons) when logical_bounds was fed directly to
            # form_regions(). Design mechanic 1 is explicit that plain branch
            # targets are NOT a split, only real function starts are; the real
            # ones are brsl/brasl call targets + indirect-call (bisl family)
            # return points. The rest still get full coverage regardless (the
            # entry switch cases every pc; a branch/call landing on any of
            # them just resolves via pc_to_region as an internal goto or a
            # cross-region hop -- never a missing case).
            from find_spu_functions import collect_brsl_targets
            region_starts = set(collect_brsl_targets(insns))
            for ins in insns:
                if ins.mnemonic in ("bisl", "bisld", "bisle"):
                    region_starts.add(ins.addr + 4)
        else:
            # --functions gave an explicit, non-over-seeded boundary list (or
            # main() fell back to the single whole-image span); use it as-is.
            region_starts = {s for s, _e in logical_bounds}

    lifter = SPULifter(trace=args.trace)
    lifter.header_name = args.header_name
    lifter.register_name = args.register_name
    lifter.func_prefix = args.func_prefix
    lifter.bi_r0_jump = compute_bi_r0_jumps(insns, logical_bounds)
    if lifter.bi_r0_jump:
        print(f"  {len(lifter.bi_r0_jump)} `bi $r0` computed-jump site(s) "
              f"(r0 reloaded via lqa/lqr): "
              f"{', '.join(f'0x{a:X}' for a in sorted(lifter.bi_r0_jump))}")
    os.makedirs(args.output, exist_ok=True)
    hp = os.path.join(args.output, args.header_name)
    sp = os.path.join(args.output, args.source_name)

    if args.regions:
        # s41 SPU REGION LIFT: split the WHOLE image into regions from the
        # real (pre-seed-all) function boundaries + a size cap, register
        # every pc -> containing region (design mechanic 1/3; review (g)).
        regions = form_regions(insns, region_starts, args.region_cap)
        pc_to_region: dict = {}
        for (rs, re_) in regions:
            for insn in insns:
                if rs <= insn.addr < re_:
                    pc_to_region[insn.addr] = rs
        for (rs, re_) in regions:
            lifter.lift_region(insns, rs, re_, pc_to_region)

        header_text = lifter.emit_region_header()
        source_text = lifter.emit_region_source(pc_to_region)
        with open(hp, "w") as f:
            f.write(header_text)
        with open(sp, "w") as f:
            f.write(source_text)

        print(f"Wrote {hp}")
        print(f"Wrote {sp}")
        print(f"  REGION LIFT: {len(regions)} region(s) (cap={args.region_cap}), "
              f"{len(insns)} insn(s) total")
        for (rs, re_) in regions:
            n = sum(1 for a in range(rs, re_, 4) if a in pc_to_region)
            print(f"      spu_region_{rs:08X} [0x{rs:X}, 0x{re_:X}): {n} insn(s)")
        if lifter.region_fallback_hits:
            print(f"  WARNING: {lifter.region_fallback_hits} cross-region call/branch "
                  f"target(s) fell back to the global indirect dispatcher (not found "
                  f"in the region owner map -- investigate before trusting the lift).")
        if lifter.unresolved_calls:
            print(f"  WARNING: {len(lifter.unresolved_calls)} brsl/brasl call(s) with "
                  f"UNRESOLVED targets lifted as NO-OPS (dropped calls = miscompile!): "
                  + ", ".join(f"0x{a:X}" for a in lifter.unresolved_calls[:12])
                  + (" ..." if len(lifter.unresolved_calls) > 12 else ""))
        if lifter.unsupported:
            total = sum(lifter.unsupported.values())
            print(f"  {total} unsupported instruction(s) across "
                  f"{len(lifter.unsupported)} mnemonic(s):")
            for mn, n in sorted(lifter.unsupported.items(), key=lambda kv: -kv[1]):
                print(f"      {mn:<10s} {n}")

        # [REV] 1 HARD ASSERTION (design's own required check): every
        # `g_spu_trampoline_fn =` site in the generated source must be
        # preceded, on the SAME line, by a `ctx->pc = ` store -- every
        # trampoline-set emission in this file is a single-line block, so a
        # same-line substring-position check is exact, not a heuristic.
        total_hops = 0
        bad_hops = []
        for lineno, line in enumerate(source_text.splitlines(), 1):
            idx = line.find("g_spu_trampoline_fn =")
            if idx < 0:
                continue
            total_hops += 1
            if "ctx->pc = " not in line[:idx] and "ctx->pc=" not in line[:idx]:
                bad_hops.append((lineno, line.strip()))
        if bad_hops:
            print(f"  ASSERTION FAILED: {len(bad_hops)}/{total_hops} "
                  f"g_spu_trampoline_fn site(s) missing a preceding ctx->pc store "
                  f"(the [REV] 1 emitter invariant is violated):")
            for ln, txt in bad_hops[:20]:
                print(f"      line {ln}: {txt}")
            sys.exit(1)
        print(f"  PASS: emitter invariant holds -- {total_hops}/{total_hops} "
              f"g_spu_trampoline_fn site(s) have ctx->pc materialized first")
        return

    lifter.func_starts = {s for s, e in bounds}  # for fall-through tail-call chaining
    for s, e in bounds:
        lifter.lift_function(insns, s, e)

    with open(hp, "w") as f:
        f.write(lifter.emit_header())
    with open(sp, "w") as f:
        f.write(lifter.emit_source())

    print(f"Wrote {hp}")
    print(f"Wrote {sp}")
    print(f"  {len(lifter.functions)} function(s) lifted")
    print(f"  {len(lifter.call_targets)} call target(s)")
    if lifter.unresolved_calls:
        print(f"  WARNING: {len(lifter.unresolved_calls)} brsl/brasl call(s) with "
              f"UNRESOLVED targets lifted as NO-OPS (dropped calls = miscompile!): "
              + ", ".join(f"0x{a:X}" for a in lifter.unresolved_calls[:12])
              + (" ..." if len(lifter.unresolved_calls) > 12 else ""))
    if lifter.unsupported:
        total = sum(lifter.unsupported.values())
        print(f"  {total} unsupported instruction(s) across "
              f"{len(lifter.unsupported)} mnemonic(s):")
        for mn, n in sorted(lifter.unsupported.items(), key=lambda kv: -kv[1]):
            print(f"      {mn:<10s} {n}")


if __name__ == "__main__":
    main()
