#!/usr/bin/env python3
"""WB coverage report: aggregates the generation metrics, differential
verdicts, assembly audits, and microbenchmarks into one markdown report.

Inputs (whatever exists is used; missing lanes are reported as such):
    scratch/wbgen/report.json + scratch/wbgen/metrics/*.json
    scratch/wbdiff/report*.json
    scratch/wbaudit/*.json
    scratch/wbbench/report.json

Usage:  py -3 tools/spu_wb_report.py [--out docs/SPU_WB_REPORT.md]
"""

import argparse
import glob
import json
import os
import sys
from collections import Counter, defaultdict

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)


def load(path):
    try:
        return json.load(open(path))
    except (OSError, json.JSONDecodeError):
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "docs",
                                                  "SPU_WB_REPORT.md"))
    args = ap.parse_args()

    L = []
    W = L.append
    W("# Whole-block SPU backend — coverage and verification report")
    W("")
    W("_Generated by tools/spu_wb_report.py from the scratch evidence of the"
      " current worktree. Regenerate after any lifter or corpus change._")
    W("")

    # ---- generation metrics -------------------------------------------
    metrics = {}
    for p in sorted(glob.glob(os.path.join(ROOT, "scratch", "wbgen",
                                           "metrics", "*.json"))):
        m = load(p)
        if m:
            metrics[os.path.basename(p)[:-5]] = m
    if metrics:
        tot = Counter()
        fb_reasons = Counter()
        for m in metrics.values():
            for k in ("n_insns", "n_insns_compiled", "n_blocks",
                      "n_blocks_compiled", "n_blocks_helper_free",
                      "kernel_native", "kernel_wrapped", "const_folded",
                      "cse_hits", "dce_dropped", "ls_load_forwarded",
                      "gpr_loads", "gpr_stores", "ls_loads", "ls_stores",
                      "channel_ops", "calls", "trampolines"):
                tot[k] += m.get(k, 0)
            for _pc, r in m.get("fallback_blocks", []):
                fb_reasons[r] += 1
        W("## Static lowering coverage")
        W("")
        W(f"- Placements generated: **{len(metrics)}**")
        W(f"- Static SPU instructions: **{tot['n_insns']:,}**; inside "
          f"whole-block-compiled blocks: **{tot['n_insns_compiled']:,} "
          f"({100*tot['n_insns_compiled']/max(1,tot['n_insns']):.2f}%)**")
        W(f"- Basic blocks: {tot['n_blocks']:,}; compiled "
          f"**{tot['n_blocks_compiled']:,} "
          f"({100*tot['n_blocks_compiled']/max(1,tot['n_blocks']):.1f}%)**; "
          f"fully helper-free **{tot['n_blocks_helper_free']:,} "
          f"({100*tot['n_blocks_helper_free']/max(1,tot['n_blocks_compiled']):.1f}%"
          f" of compiled)**")
        W(f"- Lowered ALU operations: {tot['kernel_native']:,} native SIMD + "
          f"{tot['kernel_wrapped']:,} scalar-wrapped "
          f"(**{100*tot['kernel_native']/max(1,tot['kernel_native']+tot['kernel_wrapped']):.1f}%"
          f" native**)")
        W(f"- Whole-block optimization: {tot['const_folded']:,} constants "
          f"folded, {tot['cse_hits']:,} CSE hits, {tot['dce_dropped']:,} dead "
          f"ops dropped, {tot['ls_load_forwarded']:,} LS loads forwarded")
        W(f"- Emitted context traffic: {tot['gpr_loads']:,} register loads + "
          f"{tot['gpr_stores']:,} stores for {tot['n_insns_compiled']:,} "
          f"instructions "
          f"({(tot['gpr_loads']+tot['gpr_stores'])/max(1,tot['n_insns_compiled']):.2f}"
          f" per instruction; the FAST lane pays one store per writing "
          f"instruction plus one load per operand)")
        W(f"- Remaining per-block fallbacks by reason: "
          + ", ".join(f"{r} = {n}" for r, n in fb_reasons.most_common()))
        W("")
        W("### Remaining helper categories inside compiled blocks")
        W("")
        W("- Platform (by design, genuinely dynamic): channel ops "
          f"({tot['channel_ops']:,} sites), calls/dispatch "
          f"({tot['calls']:,} call sites, {tot['trampolines']:,} trampolines), "
          "DMA/MFC and reservations behind spu_wrch/spu_rdch.")
        W("- LS hook (by design): yz_tagread_repair_read on every LS read "
          f"({tot['ls_loads']:,} static LS load sites).")
        W("- Scalar-wrapped kernels (bit-exact by construction): the xfloat "
          "float family, double-precision family, int<->float conversions, "
          "frest/frsqest/fi, clz/gbh/gbb, and variable halfword shifts "
          f"({tot['kernel_wrapped']:,} sites).")
        W("")
        W("| placement | insns | blocks compiled | helper-free | native ALU % |")
        W("|---|---:|---:|---:|---:|")
        for stem, m in sorted(metrics.items()):
            kn, kw = m.get("kernel_native", 0), m.get("kernel_wrapped", 0)
            W(f"| {stem} | {m['n_insns']:,} | {m['n_blocks_compiled']}/"
              f"{m['n_blocks']} | {m.get('n_blocks_helper_free','-')} | "
              f"{100*kn/max(1,kn+kw):.1f}% |")
        W("")

    # ---- whole-job lane (stage 2) --------------------------------------
    wj_metrics = {}
    for p in sorted(glob.glob(os.path.join(ROOT, "scratch", "wjgen",
                                           "metrics", "*.json"))):
        m = load(p)
        if m:
            wj_metrics[os.path.basename(p)[:-5]] = m
    if wj_metrics:
        t = Counter()
        for m in wj_metrics.values():
            for k in ("n_insns", "n_insns_compiled", "n_blocks",
                      "n_blocks_compiled", "n_blocks_helper_free",
                      "wj_units", "wj_groups", "wj_entries",
                      "wj_interior_blocks", "wj_intra_gotos",
                      "wj_entry_loads", "wj_publish_stores",
                      "kernel_native", "kernel_wrapped"):
                t[k] += m.get(k, 0)
        W("## Whole-job lane (stage 2)")
        W("")
        W(f"- {len(wj_metrics)} placements compiled into "
          f"**{t['wj_units']:,} units / {t['wj_groups']:,} group functions** "
          f"with **{t['wj_entries']:,} entry pcs** — "
          f"**{t['wj_interior_blocks']:,} of {t['n_blocks_compiled']:,} "
          f"compiled blocks ({100*t['wj_interior_blocks']/max(1,t['n_blocks_compiled']):.1f}%)"
          f" are interior**: no entry-switch case, registers carried across "
          f"them in host locals.")
        W(f"- Intra-group transfers converted to plain gotos: "
          f"{t['wj_intra_gotos']:,} (each was a dispatch-visible hop or a "
          f"per-block reload boundary in earlier lanes).")
        W(f"- Publication traffic: {t['wj_publish_stores']:,} barrier stores "
          f"for {t['n_insns_compiled']:,} instructions "
          f"({t['wj_publish_stores']/max(1,t['n_insns_compiled']):.3f} per "
          f"instruction).")
        W("")
    wj_diffs = []
    for p in sorted(glob.glob(os.path.join(ROOT, "scratch", "wjdiff",
                                           "report*.json"))):
        d = load(p)
        if d:
            wj_diffs.extend(d)
    if wj_diffs:
        v = Counter(e.get("verdict") for e in wj_diffs)
        st_ok = sum(1 for e in wj_diffs if e.get("static_table", {}).get("ok"))
        tm = sum(e.get("match", 0) for e in wj_diffs)
        tx = sum(e.get("mismatch", 0) for e in wj_diffs)
        ti = sum(e.get("inconclusive", 0) for e in wj_diffs)
        W(f"### WJ differential: {len(wj_diffs)} placements — "
          + ", ".join(f"{k} = {n}" for k, n in v.most_common())
          + f"; windows {tm} MATCH / {tx} MISMATCH / {ti} inconclusive; "
          f"static every-pc proofs {st_ok}/{len(wj_diffs)} exact.")
        W("")
    wj_audits = {}
    for p in sorted(glob.glob(os.path.join(ROOT, "scratch", "wjaudit",
                                           "*.json"))):
        a = load(p)
        if a and "wb" in a:
            wj_audits[a.get("stem", os.path.basename(p)[:-5])] = a
    if wj_audits:
        W("### WJ assembly audit")
        W("")
        W("| placement | WJ insns | FAST insns | ratio | WJ gpr L/S | violations |")
        W("|---|---:|---:|---:|---|---|")
        for stem, a in sorted(wj_audits.items()):
            wjs, fs = a["wb"], a.get("fast")
            ratio = (f"{wjs['insns']/fs['insns']:.3f}"
                     if fs and fs.get("insns") else "-")
            W(f"| {stem} | {wjs['insns']:,} | "
              f"{fs['insns'] if fs else 0:,} | {ratio} | "
              f"{wjs['gpr_loads']}/{wjs['gpr_stores']} | "
              f"{len(wjs.get('violations', {})) or 'none'} |")
        W("")

    # ---- differential -------------------------------------------------
    diffs = []
    for p in sorted(glob.glob(os.path.join(ROOT, "scratch", "wbdiff",
                                           "report*.json"))):
        d = load(p)
        if d:
            diffs.extend(d)
    if diffs:
        W("## Differential verification (DIAG instruction twin vs WB)")
        W("")
        v = Counter(e.get("verdict") for e in diffs)
        n_st_ok = sum(1 for e in diffs if e.get("static_table", {}).get("ok"))
        W(f"- Placements run: **{len(diffs)}** — verdicts: "
          + ", ".join(f"{k} = {n}" for k, n in v.most_common()))
        W(f"- Static every-pc registration proof: **{n_st_ok}/{len(diffs)} "
          f"placements exact** (every instruction pc registered; WB leaders "
          f"cased; every fallback pc routed to precisely the FAST twin's own "
          f"mapping)")
        tot_m = sum(e.get("match", 0) for e in diffs)
        tot_x = sum(e.get("mismatch", 0) for e in diffs)
        tot_i = sum(e.get("inconclusive", 0) for e in diffs)
        W(f"- Matrix windows: **{tot_m} MATCH / {tot_x} MISMATCH / {tot_i} "
          f"inconclusive** (inconclusive = the per-instruction reference "
          f"exceeded its dispatch/time budget, the s50-documented class)")
        W("")
        W("| placement | verdict | match | mismatch | inconclusive | static |")
        W("|---|---|---:|---:|---:|---|")
        for e in sorted(diffs, key=lambda x: (x["family"], x["stem"])):
            st = e.get("static_table", {})
            W(f"| {e['stem']} | {e.get('verdict','?')} | {e.get('match','-')}"
              f" | {e.get('mismatch','-')} | {e.get('inconclusive','-')} | "
              f"{'ok' if st.get('ok') else st.get('first_bad','-')} |")
        W("")
        bad = [e for e in diffs if e.get("verdict") not in ("MATCH",)]
        if bad:
            W("### Non-MATCH placements")
            W("")
            for e in bad:
                W(f"- **{e['stem']}**: {e.get('verdict')} — "
                  f"{e.get('detail') or e.get('mismatch_detail') or ''}")
            W("")

    # ---- fuzz ----------------------------------------------------------
    fz = load(os.path.join(ROOT, "scratch", "wbfuzz", "report.json"))
    if fz:
        W("## Randomized-block fuzz")
        W("")
        W(f"- {fz['match']} MATCH / {fz['mismatch']} MISMATCH / "
          f"{fz['inconclusive']} inconclusive")
        W("")

    # ---- asm audits ----------------------------------------------------
    audits = {}
    for p in sorted(glob.glob(os.path.join(ROOT, "scratch", "wbaudit",
                                           "*.json"))):
        a = load(p)
        if a and "wb" in a:
            audits[a.get("stem", os.path.basename(p)[:-5])] = a
    if audits:
        W("## Assembly audit")
        W("")
        W("| placement | WB insns | FAST insns | ratio | WB gpr L/S | FAST gpr L/S | violations |")
        W("|---|---:|---:|---:|---|---|---|")
        for stem, a in sorted(audits.items()):
            wbs, fs = a["wb"], a.get("fast")
            ratio = (f"{wbs['insns']/fs['insns']:.3f}" if fs and fs.get("insns")
                     else "-")
            W(f"| {stem} | {wbs['insns']:,} | "
              f"{fs['insns']:,} | {ratio} | "
              f"{wbs['gpr_loads']}/{wbs['gpr_stores']} | "
              f"{fs['gpr_loads']}/{fs['gpr_stores']} | "
              f"{len(wbs.get('violations', {})) or 'none'} |"
              if fs else
              f"| {stem} | {wbs['insns']:,} | - | - | "
              f"{wbs['gpr_loads']}/{wbs['gpr_stores']} | - | "
              f"{len(wbs.get('violations', {})) or 'none'} |")
        W("")

    # ---- bench ---------------------------------------------------------
    bench = load(os.path.join(ROOT, "scratch", "wbbench", "report.json"))
    if bench:
        W("## Microbenchmarks (identical architectural windows)")
        W("")
        W("| placement | timed windows | geomean FAST/WB | geomean FAST/WJ |")
        W("|---|---:|---:|---:|")
        for e in bench:
            W(f"| {e['stem']} | {e.get('n_timed_windows', 0)} | "
              f"{e.get('geomean_fast_wb', '-')} | "
              f"{e.get('geomean_fast_wj', '-')} |")
        W("")
        W("Per-window details live in scratch/wbbench/report.json "
          "(diag/fast/wb microseconds, dispatch counts).")
        W("")

    text = "\n".join(L) + "\n"
    with open(args.out, "w", newline="\n") as f:
        f.write(text)
    print(f"wrote {args.out} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
